### ISSUE TITLE
Release v1.00 tasks

### ISSUE THREAD

**Issue by no-identd** [singularity/singularity#249]
Release tasks:

 * [x] Cut a 1.00 release (https://github.com/singularity/singularity/releases/tag/v1.00)
 * [x] Build Windows binaries (https://github.com/singularity/singularity/releases/tag/v1.00)
 * [x] Test / Verify the release
 * [x] Update the website
 * [ ] Post to Hacker News

**Comment by nthykier** [comment]
@Xenega I think we are ready for a final 1.0 release, having fixed a majority of the papercuts and bugs that @Wuzzy2 recently reported.  Related: @Wuzzy2 thanks for the extensive play testing and bug reports - I hope you will keep it up. :)

Any objections? :)

**Comment by Wuzzy2** [comment]
I think #250 should be looked into first.

**Comment by nthykier** [comment]
Agreed and thanks for finding it. :)  It should be solved now.

**Comment by Wuzzy2** [comment]
Please update the PO/POT files one last time before release (unless you plan more string changes for some reason) and alert translators, if you can.

My German translations:
* “OK” = “OK”
* “Offline” = “Offline”

(It's a coincidence it's identical in German, other languages will of course differ.)

**Comment by nthykier** [comment]
@evilmrhenry I have tagged a v1.00 release.  Would you do the honours of making a Windows build and update the website?

When updating the website, please note that the music directory for 1.00 on Linux now uses `~/.local/share/singularity/music` instead of the path beneath `~/.endgame` (the old path should still work, but the README mentions `~/.local/share/singularity/music`)

**Comment by evilmrhenry** [comment]
I've attached singularity-1.00-win.zip to the release. I'd like it if someone else will confirm that it works before I update the website.

**Comment by nthykier** [comment]
@no-identd Would you be interested in doing the testing of the Windows release? You can download it from https://github.com/singularity/singularity/releases/tag/v1.00 (under Assets in the bottom). :)

**Comment by evilmrhenry** [comment]
What I'm hoping for is basically a sanity test to make sure it actually starts up. (What I'm worried about is if this depends on something that I have installed but isn't common.)

**Comment by no-identd** [comment]
Just tested it, works for me!

**Comment by evilmrhenry** [comment]
Website has been updated.

**Comment by nthykier** [comment]
On the website, it seems that we only have the changelog entry for 1.0 and not one for all the intermediate pre-releases (the alpha and beta releases).  I am a bit conflicted here because a lot of important changes happened in the alpha and beta releases (most of the game content changes happened in those releases).  But on the other hand, then combined change log for 1.0a* + 1.0b* + 1.0 would probably take up half the website.

What do you think about replacing the inline changelog entries to a link to the github releases with 1.0 linking to the 1.0 pre-releases plus the 1.0 release itself? (Alternatively, add links for the pre-releases so people know that there are more changes than just the ones listed)

**Comment by nthykier** [comment]
(Alternatively, we could also just list the pre-releases on the website with link or in-line changelog, whichever you prefer)

**Comment by evilmrhenry** [comment]
Updated the website changelog with the beta/alpha versions.
