### ISSUE TITLE
Windows executable gets malware detection

### ISSUE THREAD

**Issue by m-terlinde** [singularity/singularity#292]
Hey guys,

I wanted to try your game today but my Sophos Home made the verdict "Generic ML PUA" :D.
Some other vendors don't trust this executable as well: https://www.virustotal.com/gui/file/2d50deeed406557ad7cb642ca209d7a6cda8c6efae63c1ef65d85d16a5874fe3/detection

I suspect, that these heuristics don't like the spawning DLLs in the AppData directory. This can't be avoided, since it done by the Python packer, right?

Thanks,
Matthias

**Comment by nthykier** [comment]
That is unfortunate, indeed.

@evilmrhenry: Have you experienced something like this before on previous windows builds?

**Comment by nthykier** [comment]
@m-terlinde Have you reported this as a false-positive to Sophos? Having looked at https://github.com/pyinstaller/pyinstaller/issues/2988, then I think it is pretty much the only option we have.

**Comment by m-terlinde** [comment]
Hey Niels,

Thanks for the answer.
I have indeed a ticket pending for Sophos. If I have an update from them, I'll let you know. I hadn't had the time to report FPs to the other vendors yet.

Maybe 2988 is not completely right, they could improve the DLL spawning, but this is out of scope of this project :).

Thanks,
Matthias

Am 5. Juli 2020 09:20:48 MESZ schrieb Niels Thykier <notifications@github.com>:
>@m-terlinde Have you reported this as a false-positive to Sophos?
>Having looked at
>https://github.com/pyinstaller/pyinstaller/issues/2988, then I think it
>is pretty much the only option we have.

**Comment by evilmrhenry** [comment]
I don't know what the deal is here; I'm basically just pushing buttons that seem to work. I'll try pushing different buttons and see what happens.

**Comment by evilmrhenry** [comment]
OK, I pushed different buttons in order to get an exe that didn't pre-package all the libs, but the exe still tripped a bunch of anti-viruses:
https://www.virustotal.com/gui/file/0f744184ad04a2a9d0118225053064af056edbc7f7f0590c7d261d5e498a796c/detection
I then tried using cx_freeze, which only tripped one anti-virus: SecureAge APEX. I think if someone complains, we can just tell them to get a better anti-virus.
https://www.virustotal.com/gui/file/8b1c1a2ec3876dcb040a51a7994f4789a51b0f573a91aad9cd3a0ca0d4418889/detection
The downside is that all the libs take up 100mb, (40mb zipped) which is annoying, but livable. Any comments before I repackage the Windows release?

**Comment by m-terlinde** [comment]
Hey @evilmrhenry, thanks for the effort!

I'm a bit irritated that the second VirusTotal link references a file called "RoboDigital.exe" with an analysis time one month ago:
![grafik](https://user-images.githubusercontent.com/10097313/86539042-00a2eb80-befa-11ea-9104-cd156b26cee3.png)

But if it works: I'm fine with it! A resubmission showed no detection from a major AV brand.

**Comment by evilmrhenry** [comment]
New version up. Let me know if you have trouble with that one.

**Comment by m-terlinde** [comment]
Thanks, works for me and looks good!
