### ISSUE TITLE
Internationalization engine

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#49]
Singularity use two internalization engine : a custom one and gettext.
Remove the custom one, to be full gettext compatible.

**Comment by PeterJust** [comment]
Not sure, if this is the right place, but have a look at this:
![localization fail](https://user-images.githubusercontent.com/32579272/63760146-10f04000-c8bf-11e9-87e0-38b3a80270e7.png)
English and German text is randomly mashed together.
English: 
- Title of window (Message)
- First sentence, except tech name
German:
- Tech name
- Second sentence
- Button Text

**Comment by nthykier** [comment]
Closed as a part of #193

@PeterJust: That issue is presumably due to incomplete German translations of the title + first sentence (the first and the second sentences are from two separate "sources" with the tech name coming from a third source that is injected into the first sentence) .  The game will fallback to English where translations are missing.
