### ISSUE TITLE
Reduce discovery rate when not complete

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#81]
Idea by @PeterJust

In order to make incomplete base useful, reduce the discovery rate when the base have free space. We need a formula to handle this.

**Comment by PeterJust** [comment]
This could be one solution. It would punish you for filling up your base though. And I think the whole point of building a warehouse is to concentrate CPU power in one place, in order to generate less discovery rate compared to lots of datacenters. Also: where would be the benefit of a large warehouse to a small one, if discovery rate simply scales with installed CPU power?
I suggest to balance the discovery rate of the warehouses in a way, that they are usually discovered after having paid themselves off, plus some net profit. This way, you would be constantly challenged to rebuild your "warehouse fleet", while still being able to progress.

If you still want to try reducing the (d)iscovery rate proportional to (c)urrent space usage: d = (d_max - d_min) * c/m + d_min, where m is the (m)aximum space of the base and d_max/d_min define the maximum/minimum amout of discovery rate supposed to be there.

**Comment by rofl0r** [comment]
my view is that base discovery should be based on realistic possibilities. IMO the most critical phase for discovery is when you build a base, or put new equipment there. if a base is fully equipped, self-sufficient with own power generator and all kinds of stealth technology and fenced off, the chance for discovery should be almost zero (especially in 3rd world countries).

**Comment by PeterJust** [comment]
In general I'd agree. But I'd rather play a well designed(, maybe simplyfied) game than a complex but realistic simulation. (Thus I prefer Kerbal Space Program over Orbiter.)
At the moment, Singularity is pretty abstract using some interesting mechanics pitched against each other. I would personally prefer the game to stay abstract and not introduce this much detail. Therefore I would sacrifice a realistic discovery model in order to keep the game simple (-> KISS). 

So I think the constant discovery rate suffices, if it is well balanced. Making it action-dependent introduces lots of complexity. And the location dependency is cared for by the randomised location attributes. Bonus: This way, current "3rd world countries" aren't discriminated against ;)

**Comment by Quix0r** [comment]
Maybe have both together? Means, you have 2 models, realistic and abstract/arcade so both parties are having their game they wish.

**Comment by Xenega** [comment]
Realistic and arcade game is another problem. Don't mix it with this issue. (You can open a new issue) For now, the priority is to have a balanced game.

@PeterJust 
Non-constant discovery rate will appear sooner or later. In fact, there already modifier but hidden. It's not a problem. Player can have incentive to prefer big base instead of partial bases if the discovery rate is less important for one big base than two partial base. Depends of formula used.

**Comment by Xenega** [comment]
For now, we will abandon this idea.
