### ISSUE TITLE
Warning screen after pausing the game / "jobs" slider

### ISSUE THREAD

**Issue by PeterJust** [singularity/singularity#83]
There is this warning screen popping up every time the game was paused and the cpu pool overflows when the game continues. This is a bit annoying, as I deliberately leave the "jobs" slider untouched. The unused CPU is used for jobs anyway, so I don't see why I should bother.
Here are some suggestions:
- Just remove the "jobs" slider, as it is seemingly pointless
- always default the "jobs" slider position on "remaining CPU". This is equivalent to what is happening with the overflow right now, except that the overflow is cared for by the jobs slider positioning
- make the warning screen a one time event, or at least add an option to "not show this message again"

**Comment by Quix0r** [comment]
I vote for first one.

**Comment by Xenega** [comment]
The job slider is important, for new players and others, so we cannot remove it. So no first option. (never, sorry)

The second options is not good too. This warning allows to be sure the player knows there are some CPU available to avoid he forgot to allocate it. The problem is you deliberately don't use the jobs slider.

Warning was intended to be one-time event.

**Comment by Xenega** [comment]
The only thing and didn't do is the "not show this message again" button. I added it as TODO.

**Comment by nthykier** [comment]
@Xenega: Great work! It is a pleasure to be able to disable the warning. :)

**Comment by Xenega** [comment]
@nthykier I personally love that warning, but it's my taste ;)
